### ISSUE TITLE
Support other constant disassembling strategies

### ISSUE THREAD

**Issue by sulir** [sulir/edigen#25]
In addition to currently supported big-endian and little-endian, custom strategies like "bit reverse" should be supported.

One option is to use formatting character modifiers: e.g., `%+d` for big-endian, `%*d` for bit-reverse.

**Comment by vbmacher** [comment]
Just to be complete, in the email I've suggested different solution:

```
instruction = "JMP": i8;

i8 = i8: i8(8);

%%

"%s" = instruction i8(reverse);
```

where the `reverse` is a predefined method in the disassembler template. The advantage is that there can be more strategies in the future, potentially some mapping of a number to some specific string constant, etc. And it can work for littel/big endian as well as the reverse strategy.

Your suggestion is nice, but it is not general and it involves learning new formats. It will be good to stick with existing Java string format (and potentially extend ours formatter, e.g. to support something like "%04d", etc. ).

**Comment by sulir** [comment]
The support for custom decoding strategies was added. The disassembler template is quite large, so some of the nested classes (`MnemonicFormat`, `Parameter`) could be moved to emuLib if desirable.

**Comment by vbmacher** [comment]
Thanks for implementing the feature. I didn't test it so far, but I will during this week.

Regarding the classes `MnemonicFormat` and `Parameter` - I don't see general use of those except edigen itself, and `Disassembler` template in particular. Which means it shouldn't be part of emuLib. However, I see that there's a need for some edigen "runtime library", which emulib served as one so far. 

So to keep it simple, I think we can keep it like this, and just put all edigen "stuff" into separate package, like `emulib.edigen` or something similar. You're free to do it.

**Comment by sulir** [comment]
I think I will leave the nested classes in the template for now, since they allow the user to modify, e.g., strategies if necessary. They are also strongly tied to the template, so they tend to be changed simultaneously with it.

Regarding the disassembling strategies, I'm closing this issue. In case of problems, it can be reopened at any time.
